[package]
name = "keypair-secp256k1"
version = "1.0.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
secp256k1 = { version = "0.30.0", features = ["rand"] }
sha3 = "0.10.5"
hex = "0.4.3"

[dev-dependencies]
criterion = "0.4.0"

[[bin]]
name = "keypair-secp256k1"
path = "src/lib.rs"